### ISSUE TITLE
Add .editorconfig to enforce code style

### ISSUE THREAD

**Issue by tonghoangvu** [7zones/chongluadao-extension#42]
I saw that the frontend project does not have ESLint. It's just a Chrome extension, so ESLint may be unnecessary. But this

![image](https://user-images.githubusercontent.com/64119341/120137609-eb643900-c1fe-11eb-82fa-dfc42e8e38b9.png)

and this

![image](https://user-images.githubusercontent.com/64119341/120137664-046cea00-c1ff-11eb-922b-1a16f8d047d0.png)

are really annoying (trailing spaces and have no empty line at the end).

I want to add support for EditorConfig to this project. Basically, it's just a `.editorconfig` file with some useful rules. It helps write better code. You also need to add a plugin to support EditorConfig.

More details about it https://editorconfig.org/.

Thanks.

**Comment by locmai0808** [comment]
![image](https://user-images.githubusercontent.com/18728001/120259716-4ae73680-c249-11eb-8ae8-6a16cc5f7f7e.png)
Example of eslint working in this repo. 
Can add 
```
  "files.trimTrailingWhitespace": true,
  "files.insertFinalNewline": true,
```
to vscode's settings json to fix trailing white spaces and no final new line issue.

**Comment by tonghoangvu** [comment]
Oh, I solved the problem. The `main` branch contains an ESLint configuration file, but the `dev` branch not.
And how about linter for HTML and CSS files. I think the code style also needs to be consistent.
